name: DreamHelper
main: com.mrsweeter.dreamhelper.DreamHelper
version: 3.0
author: MrSweeter
description: A helper bot

commands:
    dhreload:
        description: Reload config !
        usage: §c/dhreload
        permission: dreamhelper.reload
    dhticket:
        description: Submit a ticket !
        usage: §c/dhticket <your message>
        permission: dreamhelper.ticket.send
    dhtickets:
        description: Show all open tickets !
        usage: §c/dhtickets -a/-c
        permission: dreamhelper.ticket.seen
    dhtaketicket:
        description: Take a ticket !
        usage: §c/dhtaketicket nb
        permission: dreamhelper.ticket.take
    dhcloseticket:
        description: Close a question !
        usage: §c/dhcloseticket nb
        permission: dreamhelper.ticket.close
    dhreplyticket:
        description: Reply to a ticket !
        usage: §c/dhreplyticket nb <reply>
        permission: dreamhelper.ticket.reply
    dhdeleteticket:
        description: Delete a ticket from DB or config file !
        usage: §c/dhdeleteticket nb
        permission: dreamhelper.ticket.delete
    dhpurgetickets:
        description: Delete a ticket from DB or config file !
        usage: §c/dhpurgeticket -a/-c
        permission: dreamhelper.ticket.purge
    dhcheckticket:
        description: Check a ticket from DB or config file !
        usage: §c/dhcheckticket nb
        permission: dreamhelper.ticket.check
    dhthelp:
        description: See help for DreamHelper
        usage: §c/dhhelp
        permission: dreamhelper.ticket.help
